module.exports = {
    STATUS: {
      SUCCESS: "SUCCESS",
      ERROR: "FAILURE",
      EXCEPTION: "EXCEPTION",
    },
    CODE: {
      OK: 200,
      NON_AUTHORITIVE_INFORMATION: 203,
      PARTIAL_CONTENT: 206,
      BAD_REQUEST: 400,
      UNAUTHORIZED: 401,
      FORBIDDEN: 403,
      NOT_FOUND: 404,
      INTERNAL_SERVER_ERROR: 500,
      SERVICE_UNAVAILABLE: 503,
    },
}